name: Build and Publish to GitHub Release

on:
  push:
    branches:
      - main  # 在推送到 `main` 分支时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest  # 使用 Ubuntu 作为构建环境

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2  # 获取代码库

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # 设置 .NET SDK 版本

      - name: Restore dependencies
        run: dotnet restore  # 恢复依赖项

      - name: Build the application
        run: dotnet build --configuration Release  # 构建项目

      - name: Publish the application
        run: dotnet publish --configuration Release --output ./publish  # 打包发布

      - name: Create Release on GitHub
        uses: softprops/action-gh-release@v1  # 用于创建 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub 自动提供的访问令牌
        with:
          files: ./publish/*  # 发布所有打包的文件
